# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-22 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180921_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
